---
sample_id:
  type: 'String'
  required: true
  help: 'Sample ID'
output_dir:
  type: 'Path'
  mode: 'w'
  required: true
  help: 'Absolute path to output directory'
apptainer_library:
  type: 'Path'
  mode: 'r'
  required: false
  help: 'Absolute path to Apptainer library directory'
apptainer_cache:
  type: 'Path'
  mode: 'w'
  required: false
  help: 'Absolute path to Apptainer cache directory'
input:
  type: 'Namespace'
  required: true
  help: 'Input samples'
  elements:
    coverage:
      type: 'CoverageNamespace'
      required: true
      help: 'Input coverage for sample'
      elements:
        Qualimap:
          type: 'Path'
          mode: 'r'
          required: false
          help: 'Qualimap genome coverage output path'
